name: Docker Image CI

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Docker Login
      uses: azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com
        username: $GITHUB_ACTOR
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Docker Build & Push
      run: |
        export DOCKER_TAG=docker.pkg.github.com/$GITHUB_REPOSITORY/todoist2mqtt:${GITHUB_REF#refs/heads/}
        echo "Building branch: $GITHUB_REF"
        echo "      at commit: ${{ github.sha }}"
        echo "   triggered by: ${{ github.event_name}}"
        echo "Pushing to:      $DOCKER_TAG"
        docker build . -t $DOCKER_TAG 
        docker push $DOCKER_TAG
    
